//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateSowNamespace.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateSowNamespace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Customer%.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\N\QA\Quotations\F xxxx %Customer% %Title%.
        /// </summary>
        internal static string DEST_DIR {
            get {
                return ResourceManager.GetString("DEST_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakm8ProjectsDept.
        /// </summary>
        internal static string emailPassword {
            get {
                return ResourceManager.GetString("emailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string emailServer {
            get {
                return ResourceManager.GetString("emailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trakm8Projects@gmail.com.
        /// </summary>
        internal static string emailSource {
            get {
                return ResourceManager.GetString("emailSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F xxxx.
        /// </summary>
        internal static string FSNumberToken {
            get {
                return ResourceManager.GetString("FSNumberToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FS xxx ,  Client Name , Project Title , Short Project Description , Expected Date completion,.
        /// </summary>
        internal static string HeaderLine {
            get {
                return ResourceManager.GetString("HeaderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\N\QA\Quotations\FunctionalSpecRegister.csv.
        /// </summary>
        internal static string RegisterLocation {
            get {
                return ResourceManager.GetString("RegisterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\N\QA\Quotations\zTemplate\F xxxx %Customer% %Title%.
        /// </summary>
        internal static string SOURCE_DIR {
            get {
                return ResourceManager.GetString("SOURCE_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Title%.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
